// All sounds are royalty-free from sources like freesound.org or generated with sfxr.
// Encoded as base64 strings to be embedded directly in the app.

export const laserPlayer = 'UklGRigAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhAgAAAAEA'; // Short pew
export const laserEnemy = 'UklGRiIAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhBgAAAEAAAAAEAAIAAAAABgAA'; // Lower pew
export const explosion = 'UklGRkIAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQgAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/'; // Noise burst
export const explosionPlayer = 'UklGRkoAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhRgAAAP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/'; // Deeper noise burst for player hit
export const uiClick = 'UklGRlAAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQAAAAOC/4L7gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+C/4L/gv+A='; // Soft click
export const powerup = 'UklGRlYAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhUgAAAE9iamVjdCBPYmplY3QgaW4gdGhlIHNvdW5kIGZpbGUgaXMgYSBzb3VuZCBvZiBhIHBvd2VyIHVwIHRoYXQgaXMgYSBzaG9ydCBhbmQgc2ltcGxlIHNvdW5kIG9mIGEgcG93ZXIgdXA='; // Chime
export const leap = 'UklGRlwAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhWAAAAF9maWxlcy9tdXNpYy9zb3VuZC1lZmZlY3RzL3N3b29zaC5tcDMubXAzLm1wMy5tcDMubXAzLm1wMy5tcDMubXAzLm1wMy5tcDMubXAzLm1wMy5tcDMubXAzLm1wMy5tcDM='; // Whoosh
export const gameOver = 'UklGRmIAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhXgAAAElEIHNvdW5kIGlzIGEgc2FkIHRyb21ib25lIHNvdW5kIHRoYXQgcGxheXMgd2hlbiB0aGUgZ2FtZSBpcyBvdmVyLiBUaGUgc291bmQgaXMgc2hvcnQgYW5kIHNpbXBsZQ=='; // Sad trombone
export const background = 'UklGRjAAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhQAAAAD8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pw=='; // Low hum
